name: travel
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  loading_overlay: ^0.3.0
  date_format: ^2.0.4
  # flutter_datetime_picker: ^1.5.1
  # firebase_core: ^1.0.1
  cloud_firestore: ^3.1.0
  firebase_auth: ^3.2.0
  # geolocation: ^1.1.2
  # geocoder: ^0.2.1
  flutter_google_places: ^0.3.0
  cupertino_icons: ^1.0.2
  image_picker: ^0.7.5+2
  get_it: ^6.0.0
  provider: ^5.0.0
  shared_preferences: ^2.0.5
  shimmer: ^1.1.2
  # dio: ^4.0.0-prev2
  dio: ^4.0.0
  fluro: ^2.0.3
  path_provider: ^2.0.1
  connectivity: ^3.0.2
  hexcolor: ^2.0.5
  geocoding: ^2.0.0
  geolocator: ^7.0.1
  location: ^4.3.0
  universal_ui: ^0.0.8
  image: ^3.0.2
  permission_handler: ^8.1.6
  google_maps_flutter: ^2.0.8
  google_maps_webservice: ^0.0.20-nullsafety.1
  bottom_sheet: ^1.0.1
  flutter_slidable: ^0.5.7
  flutter_dash: ^0.0.1
  timeline_tile: ^2.0.0
  sizer: ^2.0.15
  email_validator: ^2.0.1
  mime: ^0.9.7
  
dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

flutter:

  uses-material-design: true

  assets:
    - assets/icon/
    - assets/image/
    - assets/language/

  fonts:
    - family: RockSalt
      fonts:
        - asset: assets/fonts/RockSalt-Regular.ttf
    - family: Times
      fonts:
        - asset: assets/fonts/times.ttf